- name: Erstelle und pushe Änderungen zur GitOps-Repository
  run: |
    cat <<EOF > production-people-api.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-people-api
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Trojka2000/ArgoCD_GitOps.git
    path: .
    targetRevision: main
    helm:
      valueFiles:
        - values_production.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
EOF

    git config --global user.email "github-actions@github.com"
    git config --global user.name "github-actions"
    git add production-people-api.yml
    git commit --allow-empty -m "Update production-people-api.yml"
    git push

- name: Erstelle Pull Request
  uses: peter-evans/create-pull-request@v3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    title: Update production-people-api.yml
    body: |
      Dieser Pull Request enthält Aktualisierungen für das Produktions-Deployment.
      Bitte überprüfen und zusammenführen, wenn alles gut aussieht.
